dat <- read.table("R/power/mydat.txt", head=TRUE,sep=";",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric"),na.strings="?")
febdat<-subset(dat,Date=='1/2/2007' | Date == '2/2/2007')
head(febdat)
hist(febdat$Global_active_power,col="red",xlab="Global Active Power (kilowatts)")
dev.copy(png,"assgn1.png")
dev.off()
mydates <- paste(febdat$Date,febdat$Time)
mydates2 <- strptime(mydates,"%d/%m/%Y %H:%M:%S")
head(mydates2)
plot(mydates2,febdat$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowats)")
dev.copy(png,"assgn2.png")
dev.off()
with(febdat,plot(DateTime,Sub_metering_1,type="l",xlab="",ylab="Energy Sub metering"))
par(new=TRUE)
with(febdat,plot(DateTime,Sub_metering_2,type="l",xlab="",ylab="", col="red",ylim=c(min(Sub_metering_1),max(Sub_metering_1))))
par(new=TRUE)
with(febdat,plot(DateTime,Sub_metering_3,type="l",xlab="",ylab="", col="blue",ylim=c(min(Sub_metering_1),max(Sub_metering_1))))
legend("topright", lty=c(1,1,1), col = c("black","blue", "red"), legend = c("Sub Metering 1","Sub Metering 2", "Sub Metering 3"))
dev.copy(png,"assgn3.png")
dev.off()
